name: Build and Test

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Build and test on Linux
        run: |
          rm -r build
          mkdir build
          cd build
          cmake ..
          make

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: choco install cmake
      
      - name: Build and test on Windows
        run: |
          rm -r build
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019"
          cmake --build .